Repository pet-sitter/pets-next-door-api, pull requests merged in 2023-12, with the labels that each got.

#25 돌봄조건 데이터 적재가 되지 않는 오류를 해결합니다.
  cmd/import_conditions/main.go
  db/migrations/000008_create_posts_table.up.sql
  internal/postgres/condition_store.go
Labels: fix, refactor

#22 Go chi 버전 업데이트 및 돌봄급구 관련 API를 추가합니다.
  cmd/server/handler/sos_post_handler.go
  cmd/server/router.go
  docker-compose.yml
  go.mod
  go.sum
  internal/common/web.go
  internal/domain/media/resource_media.go
  internal/domain/sos_post/condition.go
  internal/domain/sos_post/service.go
  internal/domain/sos_post/sos_post.go
  internal/domain/sos_post/view.go
  internal/domain/user/user.go
  internal/postgres/resource_media_store.go
  internal/postgres/sos_post_store.go
  internal/postgres/user_store.go
  pkg/docs/docs.go
  pkg/docs/swagger.json
  pkg/docs/swagger.yaml
Labels: feat

#27 Firebase UID 필드를 사용자 조회 응답에서 제거합니다.
  cmd/server/handler/user_handler.go
  cmd/server/main.go
  internal/domain/user/view.go
  pkg/docs/docs.go
  pkg/docs/swagger.json
  pkg/docs/swagger.yaml
Labels: chore
